services:
  core.server:
    image: 'studenda.core.server'
    build:
      context: './Studenda-core'
      dockerfile: 'Studenda.Core.Server/Dockerfile'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      database_default:
        condition: 'service_healthy'
      database_identity:
        condition: 'service_healthy'
    environment:
      ConnectionStrings__Default: 'Server=database_default;Port=3306;Database=studenda_default;Uid=arkham;Pwd=secret'
      ConnectionStrings__Identity: 'Server=database_identity;Port=3306;Database=studenda_identity;Uid=arkham;Pwd=secret'
    networks:
      - 'inner'

  database_default:
    container_name: 'database_default'
    image: 'mariadb:latest'
    environment:
      MARIADB_DATABASE: 'studenda_default'
      MARIADB_USER: 'arkham'
      MARIADB_PASSWORD: 'secret'
      MARIADB_ROOT_PASSWORD: 'verysecret'
    healthcheck:
      test: 'mariadb --password=$$MARIADB_ROOT_PASSWORD --execute "SHOW DATABASES;"'
      start_period: '5s'
      interval: '2s'
      timeout: '10s'
      retries: 10
    ports:
      - '3306:3306'
    volumes:
      - 'data_default:/var/lib/mysql'
    networks:
      - 'inner'

  database_identity:
    container_name: 'database_identity'
    image: 'mariadb:latest'
    environment:
      MARIADB_DATABASE: 'studenda_identity'
      MARIADB_USER: 'arkham'
      MARIADB_PASSWORD: 'secret'
      MARIADB_ROOT_PASSWORD: 'verysecret'
    healthcheck:
      test: 'mariadb --password=$$MARIADB_ROOT_PASSWORD --execute "SHOW DATABASES;"'
      start_period: '5s'
      interval: '2s'
      timeout: '10s'
      retries: 10
    ports:
      - '3307:3306'
    volumes:
      - 'data_identity:/var/lib/mysql'
    networks:
      - 'inner'

  web.client:
    image: 'studenda.web.client'
    build:
      context: './Studenda-web'
    ports:
      - '8080:8080'
    depends_on:
      - 'core.server'

volumes:
  data_default:
  data_identity:

networks:
  inner:
